### ISSUE TITLE
Unable to import due to CAB file missing error

### ISSUE THREAD

**Issue by feledia** [microsoft/teams-powerapps-app-templates#81]
We're unable to import any of the Dataverse solution zip files to our environments. 
We get this error: 'Cab file required for importing solution with name MSFT_CommsCenter and publisher name microsoftdynamics' . 

![image](https://github.com/microsoft/teams-powerapps-app-templates/assets/153112462/e39ced04-5f10-4498-995a-e11f62848a4d)

Any ideas for what might be causing it?

**Comment by jbrewer-m** [comment]
Having the same issue when trying to import MileStones

**Comment by kachihro** [comment]
I'm having the same problem also - with MileStones - and the other sample apps.    Only for the 'dataverse' solution...

**Comment by greghodgkinson** [comment]
I have this same issue trying to import EmployeeIdeas\DataverseSolution.

**Comment by abovethebottomline** [comment]
I have the same issue trying to import Perspectives\DataverseSolution.

**Comment by DL2024Dev** [comment]
I have the same issue:

![image](https://github.com/microsoft/teams-powerapps-app-templates/assets/154428393/571bb69a-3e2c-4be5-8be7-0b7910a7ef8b)

Any ideas?

**Comment by jbmason** [comment]
![image](https://github.com/microsoft/teams-powerapps-app-templates/assets/6364013/63a1cca8-7333-4f9e-b0c2-753b76983049)
Same CAB file issue, same publisher, different solution. Microsoft help?

**Comment by feledia** [comment]
SOLUTION (of a sort :D)
Apparently the instructions in the guidance show uploading through the Teams client or the Teams admin center and our corporate IT does not allow users to upload custom apps. 
IT managed to load it through the admin center without problems.

**Comment by feledia** [comment]
Needs to be uploaded via the Teams admin center
